version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '07:30'

  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '07:30'
    groups:
      all:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
