name: Build demo

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
      - run: make demo
