name: Build demo

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
          activate-environment: true
          cache-dependency-glob: 'pyproject.toml'
      - run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
      - run: make devinstall
      - run: make demo
